# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 0b760ef9bae29847218f933e8781cd81ef02ce91b43d8876faf1acc142b9aa7f30c6a78741196f21b5fa14f4a52fb62c6fdfac9ca39745f13141907d36b7a2d4

test:
  secret_key_base: 4c0157f522339bb2d2007c9fb37fb5d8dd9d4c16af1e1f66e0c90a73e7bbd33c67adce475199cded8404a2239b4f43660da99b292277f4e90bad1605169cbfcc

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
